version: "3"

services:
  pg:
    image: bitnami/postgresql
    container_name: find-a-friend-pg
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=find-a-friend-api
